# Generated by Django 5.1 on 2024-08-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nameOrig", models.CharField(max_length=100)),
                ("oldbalanceOrg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "newbalanceOrig",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("nameDest", models.CharField(max_length=100)),
                (
                    "oldbalanceDest",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "newbalanceDest",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
