# Generated by Django 5.1 on 2024-11-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
